development:
  adapter: postgresql
  database: artist_development
  host: localhost

test:
  adapter: postgresql
  database: artist_test
  host: localhost

production:
  adapter: postgresql
  database: artist_production
  host: localhost

