development:
  host: localhost
  database: talent_development

test:
  host: localhost
  database: talent_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
