development:
  host: localhost
  database: artist_development

test:
  host: localhost
  database: artist_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
