development:
  host: localhost
  database: artist_development

test:
  host: localhost
  database: artist_test

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>

production:
  host: localhost
  database: artist_production
